# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-aws-region-reduction-map
  description: Shorter AWS Region Names for Naming Things
  homepage: https://cloudposse.com/accelerate
  topics: ""

